### ISSUE TITLE
Bug: App keeps crashing

### ISSUE THREAD

**Issue by Pretender69** [runely/calendar-homey#624] opened 2024-12-17 08:59 UTC
**Homey:**
 - Firmware: 12.2.1
 - IcalCalendar version: 2.10.0
 - Calendar provider Gmail

**Additional context**
CPU Warning limit reached

**Comment by runely** [comment] 2024-12-17 19:31
Duplicate of #607

**Closed** 2024-12-17 19:35 UTC
Labels: bug
