### ISSUE TITLE
403 forbidden Office 365 calendar ics

### ISSUE THREAD

**Issue by trxxs** [runely/calendar-homey#368] opened 2022-10-18 18:57 UTC
I receive following code when sharing a calendar through outlook.com.
Followed the guide on https://homey.app/nl-be/app/no.runely.calendar/IcalCalender/
Failed to load .ics file(s): Calendar : Request failed with status code 403.
The calendar is published correctly, restarted the app to now avail.
Not sure if it's a true bug but can't get it to work.

diagnostic report: a5bfcc12-ad94-47f8-ba75-4c31f86e1a3e

**Comment by runely** [comment] 2022-10-18 19:12
Hi. The HTTP Error Code `403` is *403 Forbidden*. This error code is sent from your Office 365 Exchange and has nothing to do with the **IcalCalendar** app. If you try to open the link in a browser, you will see that if fails with `HTTP ERROR 403`.

This has to be fixed on your Exchange account. Once the link is working in your browser, it will also work in the **IcalCalendar** app.

I'm closing this issue as this isn't caused by or something that can be fixed in **IcalCalendar**. But please feel free to comment further if you have any other comments/questions regarding this.

**Closed by runely** 2022-10-18 19:12 UTC
