### ISSUE TITLE
Bug: App crashed every couple of minutes

### ISSUE THREAD

**Issue by jeesnl** [runely/calendar-homey#556] opened 2023-12-12 12:19 UTC
**Describe the bug**
The app crashed every couple of minutes  

**To Reproduce**
Connect a gmail agenda with the hidden link

**Expected behavior**

**Screenshots**

**Homey:**
 - Firmware: Newest
 - IcalCalendar version: Newest

**Additional context**
report: b5c9dac4-4bd1-40ac-958c-47a36705314a

**Comment by runely** [comment] 2023-12-12 12:48
I'm sorry but I can't reproduce these crashes.

On my own Homey Pro 2023 (as well as on my Homey 2019) i'm importing two Gmail agendas and one Exchange agenda and has never experienced any kind of crash.

My guess is that when these crashes happens your Homey has to much to do.

Could you please perform these steps and post screenshots here?

1. Be certain that `Power User` under `Experiments` on the Homey app -> Settings is activated
2. Visit my.homey.app in your computer browser and go to Insights
3. Select `Free memory MB` , `Load Average 1m %` and `Total Memory MB` under your Homey, and select `Last 24 hours` or the nearest so you get the crash on the insights
    1. Take a screenshot of these 3 insights and post here
4. Select `CPU Load %` , `Memory Usage MB` and `Under voltage %` under System, and select `Last 24 hours` or the nearest so you get the crash on the insights
    1. Take a screenshot of these 3 insights and post here
5. Select `IcalCalendar - CPU %` and `IcalCalendar - RAM MB` under Apps, and select `Last 24 hours` or the nearest so you get the crash on the insights
    1. Take a screenshot of these 2 insights and post here

**Comment by jeesnl** [comment] 2023-12-12 14:00
Attach document you asked for.
Every start of the spike in the ical memory usage is a restart of the app. At the end of the spike the app creashes .

![Screenshot 2023-12-12 14 54 03](https://github.com/runely/calendar-homey/assets/39216786/a0858341-108c-4acc-8e94-c644d162dbb8)
![Screenshot 2023-12-12 14 53 22](https://github.com/runely/calendar-homey/assets/39216786/0eb6d895-f3ed-46ac-a347-bca876e76c30)
![Screenshot 2023-12-12 14 52 30](https://github.com/runely/calendar-homey/assets/39216786/d34de0b6-394f-4689-ae7e-9df9da22b76f)
![Screenshot 2023-12-12 14 51 39](https://github.com/runely/calendar-homey/assets/39216786/3e4b2c21-c12c-436f-9cfd-fe94f6cc8f61)
![Screenshot 2023-12-12 14 10 14](https://github.com/runely/calendar-homey/assets/39216786/2cc18775-55ee-4899-ade9-ffd68747e7db)

**Comment by jeesnl** [comment] 2023-12-16 15:27
Any idea about the cause of this error?
Could it be the data in my calendar?

**Comment by runely** [comment] 2023-12-16 20:47
There's no change in the app so I have no idea why you are experiencing this.

I don't know what's in your calendar so I wouldn't know id that could cause it.

Have you tried with fewer/other calendars?

**Comment by runely** [comment] 2024-01-20 15:09
https://community.homey.app/t/app-pro-icalcalendar/80708/72?u=runely

This guy had a similar crash. He cleaned up his calendars of years of old events, and it significantly reduced the CPU usage and the crashing stopped.

As there's nothing i can do about this, im going to close this issue

**Closed by runely** 2024-01-20 15:09 UTC
Labels: bug
